### ISSUE TITLE
evm-subql can't compile with eth-providers v2.4.20

### ISSUE THREAD

**Issue by zjb0807** [AcalaNetwork/bodhi.js#519]
```
> [bodhijs_subquery-node 5/5] RUN yarn build:
#44 1.991 ---------Subql Codegen---------
#44 1.991 ===============================
#44 1.994 Loading substrate manifest...
#44 2.022 * Schema Log generated !
#44 2.023 * Schema TransactionReceipt generated !
#44 2.024 * Models index generated !
#44 2.027 * Types index generated !
#44 9.919 node_modules/@acala-network/eth-providers/lib/utils/utils.d.ts(4,43): error TS2[307](https://github.com/AcalaNetwork/bodhi.js/runs/7519216300?check_suite_focus=true#step:7:308): Cannot find module 'src/base-provider' or its corresponding type declarations.
#44 9.962 error Command failed with exit code 1.
#44 9.962 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

"@acala-network/eth-providers": "^2.4.20",
https://github.com/AcalaNetwork/bodhi.js/runs/7519216300?check_suite_focus=true

**Comment by shunjizhan** [comment]
@zjb0807 looks like it's not an issue anymore, do you think we can close it?

**Comment by zjb0807** [comment]
@shunjizhan https://github.com/AcalaNetwork/bodhi.js/blob/master/evm-subql/package.json#L34

Can you update it and see if it works?
